node {
  name     = "emqx@127.0.0.1"      # Unique node name (Erlang identity)
  cookie   = "emqxcookie"          # Secret for clustering (must match across nodes)
  data_dir = "/opt/emqx/data"      # Directory for EMQX internal data
}

cluster {
  name = emqxcl                    # Cluster name
  discovery_strategy = manual      # Manual clustering (no auto discovery)
}

dashboard {
  listeners.http {
    bind = 18083                  # Dashboard available at http://localhost:18083
  }
  default_username = "admin"      
  default_password = "public"     
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"          
  max_connections = 1000000      # Max client connections (depends on hardware)
}

authentication = []            

authorization {
  no_match = allow                
  deny_action = ignore            
  cache.enable = true             
}